export const storeConfig = {
  storeInfo: {
    name: "Aura Store",
    logo: "Aura",
    contactEmail: "hello@aurastore.com",
    contactPhone: "+1 (555) 123-4567",
    currency: "$",
  },
  socialLinks: [
    { name: "Twitter", url: "https://twitter.com" },
    { name: "Instagram", url: "https://instagram.com" },
    { name: "Facebook", url: "https://facebook.com" },
  ],
  navigation: {
    mainNav: [
      { name: "Home", href: "/" },
      { name: "Shop", href: "/shop" },
      { name: "New Arrivals", href: "/shop?sort=newest" },
      { name: "About", href: "#about" },
    ],
    footerLinks: [
      { name: "FAQ", href: "#" },
      { name: "Shipping & Returns", href: "#" },
      { name: "Privacy Policy", href: "#" },
      { name: "Terms of Service", href: "#" },
    ],
  },
  hero: {
    headline: "Elevate Your Everyday Style",
    subheadline: "Discover the new collection of premium essentials. Crafted for comfort, designed for life.",
    ctaText: "Shop the Collection",
    ctaLink: "/shop",
    image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&q=80&w=2070",
  },
  promotions: {
    bannerText: "Free shipping on all orders over $100. Use code AURA20 for 20% off.",
    isActive: true,
  },
  categories: [
    {
      id: "c1",
      name: "Clothing",
      slug: "clothing",
      image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800",
    },
    {
      id: "c2",
      name: "Accessories",
      slug: "accessories",
      image: "https://images.unsplash.com/photo-1509319117193-57bab727e09d?auto=format&fit=crop&q=80&w=800",
    },
    {
      id: "c3",
      name: "Footwear",
      slug: "footwear",
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800",
    },
  ],
  products: [
    {
      id: "p1",
      name: "Minimalist Linen Shirt",
      slug: "minimalist-linen-shirt",
      description: "A breathable, lightweight linen shirt perfect for warm days. Features a relaxed fit and button-down front.",
      price: 65,
      originalPrice: 85,
      image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=800",
      images: [
        "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=800",
        "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800",
      ],
      category: "Clothing",
      badge: "Sale",
      rating: 4.8,
      reviewCount: 124,
      colors: ["White", "Beige", "Navy"],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      featured: true,
      newArrival: false,
    },
    {
      id: "p2",
      name: "Classic Leather Backpack",
      slug: "classic-leather-backpack",
      description: "Durable full-grain leather backpack with a dedicated laptop compartment and multiple pockets for organization.",
      price: 145,
      image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800",
      images: [
        "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800",
      ],
      category: "Accessories",
      rating: 4.9,
      reviewCount: 89,
      colors: ["Brown", "Black"],
      sizes: ["One Size"],
      inStock: true,
      featured: true,
      newArrival: true,
    },
    {
      id: "p3",
      name: "Everyday Denim Jacket",
      slug: "everyday-denim-jacket",
      description: "A timeless denim jacket with a comfortable, slightly oversized fit. Made from 100% organic cotton.",
      price: 110,
      image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&q=80&w=800",
      images: [
        "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&q=80&w=800",
      ],
      category: "Clothing",
      rating: 4.6,
      reviewCount: 56,
      colors: ["Light Blue", "Indigo"],
      sizes: ["S", "M", "L"],
      inStock: true,
      featured: false,
      newArrival: true,
    },
    {
      id: "p4",
      name: "Canvas Sneakers",
      slug: "canvas-sneakers",
      description: "Classic canvas sneakers with a rubber sole. Comfortable for all-day wear.",
      price: 55,
      image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800",
      images: [
        "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800",
      ],
      category: "Footwear",
      badge: "Bestseller",
      rating: 4.7,
      reviewCount: 210,
      colors: ["White", "Black"],
      sizes: ["7", "8", "9", "10", "11"],
      inStock: true,
      featured: true,
      newArrival: false,
    },
    {
      id: "p5",
      name: "Silk Scarf",
      slug: "silk-scarf",
      description: "A luxurious 100% silk scarf with a unique printed pattern.",
      price: 45,
      image: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&q=80&w=800",
      images: [
        "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&q=80&w=800",
      ],
      category: "Accessories",
      rating: 4.5,
      reviewCount: 34,
      colors: ["Multicolor"],
      sizes: ["One Size"],
      inStock: false,
      featured: false,
      newArrival: false,
    },
    {
      id: "p6",
      name: "Wool Blend Coat",
      slug: "wool-blend-coat",
      description: "A warm and stylish wool blend coat for the winter season. Features a tailored fit.",
      price: 195,
      originalPrice: 250,
      image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&q=80&w=800",
      images: [
        "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&q=80&w=800",
      ],
      category: "Clothing",
      badge: "Sale",
      rating: 4.9,
      reviewCount: 78,
      colors: ["Camel", "Charcoal"],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      featured: true,
      newArrival: false,
    }
  ],
  testimonials: [
    {
      id: "t1",
      name: "Sarah M.",
      role: "Verified Buyer",
      content: "The quality of the clothes is incredible. I've received so many compliments on my new jacket!",
      rating: 5,
    },
    {
      id: "t2",
      name: "James T.",
      role: "Verified Buyer",
      content: "Fast shipping and excellent customer service. The backpack exceeded my expectations.",
      rating: 5,
    },
    {
      id: "t3",
      name: "Emily R.",
      role: "Verified Buyer",
      content: "Love the minimal aesthetic. Everything fits perfectly and feels premium.",
      rating: 4,
    },
  ],
  newsletter: {
    heading: "Join the Aura Community",
    description: "Subscribe to receive updates, access to exclusive deals, and more.",
    buttonText: "Subscribe",
  },
};
